# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-17 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='공지사항/뉴스 카테고리 구분', unique=True, verbose_name='카테고리'),
        ),
    ]
