# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-17 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181217_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='출처', unique=True, verbose_name='출처'),
        ),
    ]
