# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-17 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181217_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='출처', verbose_name='출처'),
        ),
    ]
