# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-15 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0015_photo_balcony'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='loca',
            field=models.CharField(blank=True, max_length=50, verbose_name='지역명'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50, verbose_name='부동산'),
        ),
    ]
